import React from "react"

export const metadata = {
  title: "OAuth Flow",
  description: "Generated by create next app"
}

export default function AuthLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <main data-theme="">
      <div className="">
        <div className="">
          <h1 className="">OAuth Flow app\auth\layout.tsx</h1>
        </div>
        <div className="">{children}</div>
      </div>
    </main>
  )
}
